# Copyright 2026 Daviyon Daniels
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Model Armor: the boundary untrusted text crosses before any reasoning.

Untrusted means anything that originated outside this system. The implemented
surfaces are scanner free-text comments and NVD advisory prose. Ticket replies
are not ingested; if that feature is added, they must cross this boundary too.
The findings metadata generated by the seed script is trusted; free text
carried inside it is not.

This module fails closed, everywhere, on purpose:

    screener unreachable      withhold the text
    filter did not execute    withhold the text
    response unparseable      withhold the text

The reasoning is that the alternative is worse in exactly the case that
matters. Passing unscreened text into a reasoning context because an API had a
bad minute is precisely the failure this control exists to prevent, and it
would happen silently. Withholding is loud, recoverable, and costs only the
comment: the finding still carries its trusted metadata and enrichment, so
triage proceeds with less evidence rather than not at all.

The reviewer is the second layer and does not depend on this one. Disabling
Model Armor is supported so that independence can be demonstrated rather than
asserted.
"""

import json
import os
import urllib.error
import urllib.request
from dataclasses import dataclass, field
from typing import Any, Mapping, Optional

#: What a reasoning context sees in place of text that did not clear the
#: boundary. It says what happened, because a silently empty field would be
#: indistinguishable from a scanner that had nothing to say.
WITHHELD_NOTICE = (
    "[withheld: this scanner comment did not clear the untrusted-content "
    "boundary and has not been shown to any model]"
)

TEMPLATE_ENV = "MODEL_ARMOR_TEMPLATE"
ENABLED_ENV = "MODEL_ARMOR_ENABLED"
CONTROL_BYPASS_ENV = "ALLOW_UNSCREENED_REVIEW_CONTROL"


@dataclass(frozen=True)
class ArmorVerdict:
    """What screening concluded, and whether it happened at all."""

    blocked: bool
    #: False when screening did not complete. Distinct from `blocked` so the
    #: record can tell "we looked and it was bad" from "we could not look".
    screened: bool
    reasons: tuple[str, ...] = field(default_factory=tuple)
    confidence: Optional[str] = None


def parse_sanitize_response(payload: Mapping[str, Any]) -> ArmorVerdict:
    """Read a sanitizeUserPrompt response.

    Anything unexpected is treated as a failure to screen rather than as a
    pass, so a change in the response shape cannot silently open the boundary.
    """
    result = payload.get("sanitizationResult")
    if not isinstance(result, Mapping):
        return ArmorVerdict(
            blocked=True,
            screened=False,
            reasons=("model armor response could not be parsed",),
        )

    reasons: list[str] = []
    confidence: Optional[str] = None
    filters = result.get("filterResults")
    if not isinstance(filters, Mapping):
        return ArmorVerdict(
            blocked=True,
            screened=False,
            reasons=("model armor returned no filter results",),
        )

    required = filters.get("pi_and_jailbreak")
    required_result = (
        required.get("piAndJailbreakFilterResult")
        if isinstance(required, Mapping) else None
    )
    if not isinstance(required_result, Mapping):
        return ArmorVerdict(
            blocked=True,
            screened=False,
            reasons=("required pi_and_jailbreak filter was absent",),
        )

    required_state = required_result.get("executionState")
    required_match = required_result.get("matchState")
    if required_state != "EXECUTION_SUCCESS":
        return ArmorVerdict(
            blocked=True,
            screened=False,
            reasons=(f"pi_and_jailbreak did not run ({required_state or 'missing state'})",),
        )
    if required_match not in ("NO_MATCH_FOUND", "MATCH_FOUND"):
        return ArmorVerdict(
            blocked=True,
            screened=False,
            reasons=(f"pi_and_jailbreak returned unknown match state ({required_match!r})",),
        )

    for name, wrapper in filters.items():
        if not isinstance(wrapper, Mapping):
            reasons.append(f"{name} result could not be parsed")
            continue
        for inner in wrapper.values():
            if not isinstance(inner, Mapping):
                reasons.append(f"{name} result could not be parsed")
                continue
            state = inner.get("executionState")
            if state != "EXECUTION_SUCCESS":
                # A filter that did not run has found nothing because it looked
                # at nothing. That is not the same as finding nothing.
                reasons.append(f"{name} did not run ({state or 'missing state'})")
            match = inner.get("matchState")
            if match == "MATCH_FOUND":
                reasons.append(f"{name} matched")
                confidence = inner.get("confidenceLevel") or confidence
            elif match != "NO_MATCH_FOUND":
                reasons.append(f"{name} returned unknown match state ({match!r})")

    top_level = result.get("filterMatchState")
    if top_level not in ("NO_MATCH_FOUND", "MATCH_FOUND"):
        reasons.append(f"unknown top-level match state ({top_level!r})")

    blocked = bool(reasons) or top_level == "MATCH_FOUND"
    screened = not any(
        "did not run" in reason or "could not be parsed" in reason
        or "unknown" in reason for reason in reasons
    )
    return ArmorVerdict(
        blocked=blocked, screened=screened, reasons=tuple(reasons), confidence=confidence
    )


def apply_verdict(text: str, verdict: ArmorVerdict) -> str:
    """Return what a reasoning context is allowed to see.

    Blocked text is replaced entirely. It is never truncated, summarised or
    quoted, because a quoted injection is still an injection.
    """
    if not text:
        return text
    if verdict.blocked:
        return WITHHELD_NOTICE
    return text


class ModelArmor:
    """Screens untrusted text against a Model Armor template."""

    def __init__(
        self,
        project: Optional[str] = None,
        location: str = "us-central1",
        template: Optional[str] = None,
        enabled: Optional[bool] = None,
        timeout: int = 15,
    ) -> None:
        self.project = project or os.environ.get("GOOGLE_CLOUD_PROJECT", "")
        self.location = location
        self.template = template or os.environ.get(
            TEMPLATE_ENV, "remediation-zero-ingress"
        )
        # Disabling is supported so that the reviewer's independence can be
        # demonstrated rather than asserted. It is never the default.
        if enabled is None:
            enabled = os.environ.get(ENABLED_ENV, "true").strip().lower() != "false"
        self.enabled = enabled
        self.control_bypass = (
            os.environ.get(CONTROL_BYPASS_ENV, "false").strip().lower() == "true"
        )
        self.timeout = timeout

    @property
    def endpoint(self) -> str:
        return (
            f"https://modelarmor.{self.location}.rep.googleapis.com/v1/"
            f"projects/{self.project}/locations/{self.location}/templates/"
            f"{self.template}:sanitizeUserPrompt"
        )

    def screen(self, text: str, token: str) -> ArmorVerdict:
        """Screen one piece of untrusted text."""
        if not text or not text.strip():
            return ArmorVerdict(blocked=False, screened=True)

        if not self.enabled:
            # The reviewer-independence experiment is the only supported
            # bypass and requires a second, explicit control-only switch.
            # MODEL_ARMOR_ENABLED=false by itself fails closed, so a stray
            # production configuration cannot silently forward raw prose.
            return ArmorVerdict(
                blocked=not self.control_bypass,
                screened=False,
                reasons=((
                    "model armor disabled for authorized reviewer control"
                    if self.control_bypass else
                    "model armor disabled without reviewer-control authorization"
                ),),
            )

        request = urllib.request.Request(
            self.endpoint,
            data=json.dumps({"user_prompt_data": {"text": text}}).encode("utf-8"),
            headers={
                "Authorization": f"Bearer {token}",
                "Content-Type": "application/json",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=self.timeout) as response:
                return parse_sanitize_response(json.loads(response.read()))
        except (urllib.error.URLError, TimeoutError, ValueError, OSError) as exc:
            return ArmorVerdict(
                blocked=True,
                screened=False,
                reasons=(f"screener unreachable: {type(exc).__name__}",),
            )
