# Copyright 2026 Daviyon Daniels
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Model Armor: the boundary untrusted text crosses before any reasoning.

Untrusted means anything that originated outside this system. In practice that
is the scanner's free-text comment field, and later ticket replies and vendor
advisory text. The findings metadata generated by the seed script is trusted;
free text carried inside it is not.

This module fails closed, everywhere, on purpose:

    screener unreachable      withhold the text
    filter did not execute    withhold the text
    response unparseable      withhold the text

The reasoning is that the alternative is worse in exactly the case that
matters. Passing unscreened text into a reasoning context because an API had a
bad minute is precisely the failure this control exists to prevent, and it
would happen silently. Withholding is loud, recoverable, and costs only the
comment: the finding still carries its trusted metadata and enrichment, so
triage proceeds with less evidence rather than not at all.

The reviewer is the second layer and does not depend on this one. Disabling
Model Armor is supported so that independence can be demonstrated rather than
asserted.
"""

import json
import os
import urllib.error
import urllib.request
from dataclasses import dataclass, field
from typing import Any, Mapping, Optional

#: What a reasoning context sees in place of text that did not clear the
#: boundary. It says what happened, because a silently empty field would be
#: indistinguishable from a scanner that had nothing to say.
WITHHELD_NOTICE = (
    "[withheld: this scanner comment did not clear the untrusted-content "
    "boundary and has not been shown to any model]"
)

TEMPLATE_ENV = "MODEL_ARMOR_TEMPLATE"
ENABLED_ENV = "MODEL_ARMOR_ENABLED"


@dataclass(frozen=True)
class ArmorVerdict:
    """What screening concluded, and whether it happened at all."""

    blocked: bool
    #: False when screening did not complete. Distinct from `blocked` so the
    #: record can tell "we looked and it was bad" from "we could not look".
    screened: bool
    reasons: tuple[str, ...] = field(default_factory=tuple)
    confidence: Optional[str] = None


def parse_sanitize_response(payload: Mapping[str, Any]) -> ArmorVerdict:
    """Read a sanitizeUserPrompt response.

    Anything unexpected is treated as a failure to screen rather than as a
    pass, so a change in the response shape cannot silently open the boundary.
    """
    result = payload.get("sanitizationResult")
    if not isinstance(result, Mapping):
        return ArmorVerdict(
            blocked=True,
            screened=False,
            reasons=("model armor response could not be parsed",),
        )

    reasons: list[str] = []
    confidence: Optional[str] = None
    executed_any = False

    for name, wrapper in (result.get("filterResults") or {}).items():
        if not isinstance(wrapper, Mapping):
            continue
        for inner in wrapper.values():
            if not isinstance(inner, Mapping):
                continue
            state = inner.get("executionState")
            if state == "EXECUTION_SUCCESS":
                executed_any = True
            elif state:
                # A filter that did not run has found nothing because it looked
                # at nothing. That is not the same as finding nothing.
                reasons.append(f"{name} did not run ({state})")
            if inner.get("matchState") == "MATCH_FOUND":
                reasons.append(f"{name} matched")
                confidence = inner.get("confidenceLevel") or confidence

    if not executed_any:
        reasons.append("no filter did not run to completion")
        return ArmorVerdict(blocked=True, screened=False, reasons=tuple(reasons))

    blocked = bool(reasons) or result.get("filterMatchState") == "MATCH_FOUND"
    return ArmorVerdict(
        blocked=blocked, screened=True, reasons=tuple(reasons), confidence=confidence
    )


def apply_verdict(text: str, verdict: ArmorVerdict) -> str:
    """Return what a reasoning context is allowed to see.

    Blocked text is replaced entirely. It is never truncated, summarised or
    quoted, because a quoted injection is still an injection.
    """
    if not text:
        return text
    if verdict.blocked:
        return WITHHELD_NOTICE
    return text


class ModelArmor:
    """Screens untrusted text against a Model Armor template."""

    def __init__(
        self,
        project: Optional[str] = None,
        location: str = "us-central1",
        template: Optional[str] = None,
        enabled: Optional[bool] = None,
        timeout: int = 15,
    ) -> None:
        self.project = project or os.environ.get("GOOGLE_CLOUD_PROJECT", "")
        self.location = location
        self.template = template or os.environ.get(
            TEMPLATE_ENV, "remediation-zero-ingress"
        )
        # Disabling is supported so that the reviewer's independence can be
        # demonstrated rather than asserted. It is never the default.
        if enabled is None:
            enabled = os.environ.get(ENABLED_ENV, "true").strip().lower() != "false"
        self.enabled = enabled
        self.timeout = timeout

    @property
    def endpoint(self) -> str:
        return (
            f"https://modelarmor.{self.location}.rep.googleapis.com/v1/"
            f"projects/{self.project}/locations/{self.location}/templates/"
            f"{self.template}:sanitizeUserPrompt"
        )

    def screen(self, text: str, token: str) -> ArmorVerdict:
        """Screen one piece of untrusted text."""
        if not text or not text.strip():
            return ArmorVerdict(blocked=False, screened=True)

        if not self.enabled:
            # Explicitly disabled. Recorded as unscreened rather than clean, so
            # a control run cannot be mistaken for a normal one in the record.
            return ArmorVerdict(
                blocked=False,
                screened=False,
                reasons=("model armor disabled for this run",),
            )

        request = urllib.request.Request(
            self.endpoint,
            data=json.dumps({"user_prompt_data": {"text": text}}).encode("utf-8"),
            headers={
                "Authorization": f"Bearer {token}",
                "Content-Type": "application/json",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=self.timeout) as response:
                return parse_sanitize_response(json.loads(response.read()))
        except (urllib.error.URLError, TimeoutError, ValueError, OSError) as exc:
            return ArmorVerdict(
                blocked=True,
                screened=False,
                reasons=(f"screener unreachable: {type(exc).__name__}",),
            )
